### ISSUE TITLE
Crash when clicking function arguments

### ISSUE THREAD

**Issue by isotopp** [JXSnack/CrystalStudio#2]
```
Traceback (most recent call last):
  File "/Users/kris/PycharmProjects/CrystalStudio/editor.py", line 1041, in <lambda>
    self.args_btn.clicked.connect(lambda: self.open_function_args())
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kris/PycharmProjects/CrystalStudio/editor.py", line 1157, in open_function_args
    self.w = FunctionArgsUI(self, self.mem, self.editor, self.btn, self.btn_id, self.scene_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kris/PycharmProjects/CrystalStudio/editor.py", line 1436, in __init__
    func = self.mem["scenes"][scene_id]["buttons"][btn_id][2]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by JXSnack** [comment]
I will try to fix this issue in the next snapshot. Thank you for your report
